# Generated by Django 4.1.7 on 2023-03-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.FloatField()),
                ('NumCuenta', models.CharField(max_length=50)),
                ('Beneficiario', models.CharField(max_length=100)),
                ('Concepto', models.TextField(max_length=200)),
                ('Banco', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Telefono', models.PositiveIntegerField()),
            ],
        ),
    ]
